apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller
  labels:
spec:
  selector:
    matchLabels:
  replicas: 1
  template:
    metadata:
      annotations:
        iam.amazonaws.com/role: "kube-secret-syncer-role"
      labels:
    spec:
      containers:
      - command:
        - /manager
        args:
        - --enable-leader-election
        env:
        - name: AWS_REGION
          value: 'us-east-1'
          image: "contentful-labs/kube-secret-syncer:latest"
        name: kube-secret-syncer
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
      terminationGracePeriodSeconds: 10
