# permissions for end users to edit syncedsecrets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: syncedsecret-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kube-secret-syncer
    app.kubernetes.io/part-of: kube-secret-syncer
    app.kubernetes.io/managed-by: kustomize
  name: syncedsecret-editor-role
rules:
- apiGroups:
  - secrets.contentful.com
  resources:
  - syncedsecrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - secrets.contentful.com
  resources:
  - syncedsecrets/status
  verbs:
  - get
