apiVersion: secrets.contentful.com/v1
kind: SyncedSecret
metadata:
  labels:
    app.kubernetes.io/name: syncedsecret
    app.kubernetes.io/instance: syncedsecret-sample
    app.kubernetes.io/part-of: kube-secret-syncer
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kube-secret-syncer
  name: syncedsecret-sample
spec:
  # TODO(user): Add fields here
