apiVersion: secrets.contentful.com/v1
kind: SyncedSecret
metadata:
  name: syncedsecret-sample-ks
  namespace: secret-sync 
spec:
  secretMetadata: 
    name: demo-service-secret 
    namespace: secret-sync 
    annotations: 
      randomkey: randomval
  data: 
    DB_NAME: database_name 
    DB_PASS: database_pass 
  secretid: secretsyncer/secret/sample
