apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kube-secret-syncer
  name: kube-secret-syncer-controller
  namespace: kube-secret-syncer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-secret-syncer
  template:
    metadata:
      annotations:
        iam.amazonaws.com/role: kube-secret-syncer-role
      labels:
        app: kube-secret-syncer
    spec:
      containers:
      - args:
        - --enable-leader-election
        command:
        - /manager
        env:
        - name: AWS_REGION
          value: us-east-1
        image: contentful-labs/kube-secret-syncer:latest
        name: kube-secret-syncer
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
      terminationGracePeriodSeconds: 10
